config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "grams#index"
    resources :grams, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gram.rb
class Gram < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
    def index
    end
    
    def new
        @gram = Gram.new
    end
    
    def create
        @gram = Gram.create(gram_params)
        if @gram.valid?
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    private
    def gram_params
        params.require(:gram).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/index.html.erb
<h1>grams!</h1>

app/views/grams/new.html.erb
<div class="booyah-box col-10 offset-1">
    <h1>New Gram</h1>
    <%= simple_form_for @gram do |f|%>
        <%= f.input :message %>
        <br />
        <%= f.submit 'Post!', class:'btn btn-primary' %>
    <% end %>
    
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grammable</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-toggleable-md navbar-light style="background-color: #e3f2fd">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to "Grammable", root_path, class: "navbar-brand" %>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
              <%= link_to new_gram_path, class: "nav-link" do %>
                <i class="fa fa-plus-circle"></i>
                New Gram
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    
    <%= yield %>
  </body>
</html>